# Generated by Django 5.2.8 on 2026-08-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', help_text='Required — buyers contact you here (WhatsApp / call).', max_length=20),
        ),
    ]
