# Generated by Django 5.2.8 on 2026-08-02 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0027_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('add_to_cart', 'Add to cart'), ('purchase', 'Purchase'), ('search', 'Search'), ('watchlist', 'Watchlist')], db_index=True, max_length=32)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_events', to='business.item')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'event_type', 'timestamp'], name='recommend_i_user_id_63b0d8_idx'), models.Index(fields=['item', 'event_type'], name='recommend_i_item_id_4d0135_idx'), models.Index(fields=['session_key', 'event_type', 'timestamp'], name='recommend_i_session_ac6cc3_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('cart_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.FloatField(db_index=True, default=0.0)),
                ('price_band', models.PositiveSmallIntegerField(default=0)),
                ('recency_score', models.FloatField(default=0.0)),
                ('avg_rating', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_features', to='business.item')),
            ],
            options={
                'indexes': [models.Index(fields=['-popularity_score'], name='recommend_i_popular_944470_idx')],
            },
        ),
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('source', models.CharField(default='co_occurrence', max_length=32)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='business.item')),
                ('similar_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='business.item')),
            ],
            options={
                'indexes': [models.Index(fields=['item', '-score'], name='recommend_i_item_id_8dc125_idx')],
                'unique_together': {('item', 'similar_item')},
            },
        ),
        migrations.CreateModel(
            name='UserFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('category_affinity', models.JSONField(blank=True, default=dict)),
                ('recent_item_ids', models.JSONField(blank=True, default=list)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('cart_count', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommend_features', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('session_key', ''), _negated=True), fields=('session_key',), name='uniq_userfeature_session')],
            },
        ),
    ]
