# Generated by Django 5.2.8 on 2026-08-02 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0023_alter_item_compare_at_price_alter_item_price'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('payment_method', models.CharField(choices=[('campus_meetup', 'Pay at Meetup'), ('cash_on_delivery', 'Cash on Delivery'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=32)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=32)),
                ('fulfillment_method', models.CharField(choices=[('campus_pickup', 'Campus Pickup / Meetup'), ('delivery', 'Delivery')], default='campus_pickup', max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('campus_location', models.CharField(blank=True, max_length=255)),
                ('address_line', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('subtotal_tan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('shipping_fee_tan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_tan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_tan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fiat_currency_code', models.CharField(blank=True, default='TZS', max_length=10)),
                ('fiat_rate_snapshot', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True)),
                ('total_fiat_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stock_restored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('unit_price_tan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total_tan', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('ready_for_pickup', 'Ready for Pickup'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='company.company')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='business.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='customer.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_order_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('campus_meetup', 'Pay at Meetup'), ('cash_on_delivery', 'Cash on Delivery'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer')], max_length=32)),
                ('amount_tan', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='customer.order')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
