# Generated by Django 5.2.8 on 2026-08-02 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_initial'),
        ('chat', '0003_message_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sold', 'Sold'), ('not_sold', 'Not sold')], db_index=True, default='pending', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('rating_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deals_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='chat.conversation')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_deals', to='business.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_deals_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DealRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_ratings_given', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_ratings', to='business.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_ratings_received', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='chat.itemdeal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemdeal',
            constraint=models.UniqueConstraint(fields=('conversation', 'item', 'buyer'), name='uniq_deal_conversation_item_buyer'),
        ),
    ]
