# Generated by Django 5.2.8 on 2025-12-26 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_item_image2_item_image3_alter_item_campus_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='preferred_meetup',
        ),
        migrations.AddField(
            model_name='item',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Compare at Price'),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_dimensions',
            field=models.CharField(blank=True, help_text='L x W x H', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='shipping_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='kg', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Product ID / SKU'),
        ),
        migrations.AddField(
            model_name='item',
            name='stock_quantity',
            field=models.IntegerField(default=1, verbose_name='Stock Quantity'),
        ),
        migrations.AddField(
            model_name='item',
            name='tax_class',
            field=models.CharField(blank=True, default='Standard', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used')], default='used', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item_images/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Image 2'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='item_images/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Base Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Product Title'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='business.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='business.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='others', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='business.item')),
            ],
        ),
    ]
