# Generated by Django 5.2.8 on 2025-12-26 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_attribute_remove_item_preferred_meetup_and_more'),
    ]

    operations = [
    ]
