# Generated by Django 5.2.8 on 2025-12-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_item_category_obj_alter_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='attributes', to='business.category'),
        ),
    ]
