# Generated by Django 5.2.8 on 2025-12-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
