# Generated by Django 5.2.8 on 2025-12-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_company_address_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Pinned to Top'),
        ),
    ]
