# Generated by Django 5.2.8 on 2025-12-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_item_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
