# Generated by Django 5.2.8 on 2025-12-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("business", "0020_district_region_alter_company_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Street, Building, or specific location",
                max_length=255,
                null=True,
            ),
        ),
    ]
