# Generated by Django 5.2.8 on 2026-08-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0022_remove_report_company_remove_review_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional higher reference price in TAN (shown struck through).', max_digits=12, null=True, verbose_name='Compare at (TAN)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Amount in Tancoin (TAN). Fiat shown on the site uses the admin exchange rate.', max_digits=12, verbose_name='Price (TAN)'),
        ),
    ]
