# Generated by Django 5.2.8 on 2026-08-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_alter_item_compare_at_price_alter_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='video',
            field=models.FileField(blank=True, help_text='Optional short clip (max 30 seconds). MP4 / WebM / MOV.', null=True, upload_to='item_videos/', verbose_name='Product video'),
        ),
    ]
