# Generated by Django 5.2.8 on 2026-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_migrate_item_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='compare_at_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional higher reference price (shown struck through).', max_digits=12, null=True, verbose_name='Compare at'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Selling price.', max_digits=12, verbose_name='Price'),
        ),
    ]
